"""initial schema baseline

Revision ID: 43685ae506e6
Revises: 
Create Date: 2026-05-14 09:56:55.589065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43685ae506e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_check_usage',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('year_month', sa.String(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('client_id', 'year_month')
    )
    op.create_table('contact_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_submissions_id'), ['id'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='usd', nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('popular', sa.Boolean(), nullable=True),
    sa.Column('features', sa.String(), nullable=False),
    sa.Column('not_included', sa.String(), nullable=False),
    sa.Column('tier_type', sa.String(), nullable=False),
    sa.Column('monthly_check_quota', sa.Integer(), nullable=False),
    sa.Column('allowed_check_categories', sa.Text(), nullable=True),
    sa.Column('features_json', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_slug'), ['slug'], unique=True)

    op.create_table('sales_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('tier_slug', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_leads_id'), ['id'], unique=False)

    op.create_table('sentiment_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('name_zh', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sentiment_platforms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentiment_platforms_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_sentiment_platforms_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('ai_telemetry_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('target_aliases_json', sa.Text(), nullable=False),
    sa.Column('queries_json', sa.Text(), nullable=False),
    sa.Column('engines_json', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_telemetry_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_telemetry_topics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_telemetry_topics_user_id'), ['user_id'], unique=False)

    op.create_table('detection_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('result_snapshot', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detection_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detection_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_records_user_id'), ['user_id'], unique=False)

    op.create_table('payment_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_session_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('checkout_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('chain', sa.String(), nullable=True),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.Column('wallet_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_sessions_stripe_session_id'), ['stripe_session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('sentiment_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('aliases_json', sa.Text(), nullable=True),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('keywords_json', sa.Text(), nullable=True),
    sa.Column('keyword_groups_json', sa.Text(), nullable=True),
    sa.Column('excludes_json', sa.Text(), nullable=True),
    sa.Column('media_allowlist_json', sa.Text(), nullable=True),
    sa.Column('notify_emails_json', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.String(), nullable=True),
    sa.Column('last_run_error', sa.Text(), nullable=True),
    sa.Column('last_run_stats', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker', name='uq_user_ticker')
    )
    with op.batch_alter_table('sentiment_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentiment_accounts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentiment_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('user_check_usage',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year_month', sa.String(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'year_month')
    )
    op.create_table('user_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_memberships_id'), ['id'], unique=False)

    op.create_table('ai_telemetry_cell_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('engine', sa.String(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('competitors_top3_json', sa.Text(), nullable=False),
    sa.Column('recommendations_json', sa.Text(), nullable=False),
    sa.Column('evidence_response_ids_json', sa.Text(), nullable=False),
    sa.Column('llm_model', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['ai_telemetry_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'query', 'engine', 'window_end', 'prompt_version', name='uq_ci_cell_window')
    )
    with op.batch_alter_table('ai_telemetry_cell_insights', schema=None) as batch_op:
        batch_op.create_index('idx_ci_topic', ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_telemetry_cell_insights_id'), ['id'], unique=False)

    op.create_table('ai_telemetry_query_hits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('engine', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('first_hit_at', sa.DateTime(), nullable=True),
    sa.Column('first_hit_response_id', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('total_hits', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['ai_telemetry_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'query', 'engine', name='uq_qh_cell')
    )
    with op.batch_alter_table('ai_telemetry_query_hits', schema=None) as batch_op:
        batch_op.create_index('idx_qh_topic', ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_telemetry_query_hits_id'), ['id'], unique=False)

    op.create_table('ai_telemetry_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['ai_telemetry_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_telemetry_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_telemetry_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_telemetry_runs_topic_id'), ['topic_id'], unique=False)

    op.create_table('ai_telemetry_topic_briefings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('kpi_snapshot_json', sa.Text(), nullable=False),
    sa.Column('top_actions_json', sa.Text(), nullable=False),
    sa.Column('delivered_email_at', sa.DateTime(), nullable=True),
    sa.Column('feedback_score', sa.Integer(), nullable=True),
    sa.Column('llm_model', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['ai_telemetry_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'period_end', 'prompt_version', name='uq_tb_period')
    )
    with op.batch_alter_table('ai_telemetry_topic_briefings', schema=None) as batch_op:
        batch_op.create_index('idx_tb_topic', ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_telemetry_topic_briefings_id'), ['id'], unique=False)

    op.create_table('sentiment_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['sentiment_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'key', name='uq_account_key')
    )
    with op.batch_alter_table('sentiment_knowledge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentiment_knowledge_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentiment_knowledge_id'), ['id'], unique=False)

    op.create_table('sentiment_run_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('stats_json', sa.Text(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['sentiment_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sentiment_run_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentiment_run_logs_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentiment_run_logs_id'), ['id'], unique=False)

    op.create_table('ai_telemetry_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('citations_json', sa.Text(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('hit', sa.Boolean(), nullable=False),
    sa.Column('hit_excerpt', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('competitors_json', sa.Text(), nullable=True),
    sa.Column('citation_domains_json', sa.Text(), nullable=True),
    sa.Column('answer_format', sa.String(), nullable=True),
    sa.Column('mention_position', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['ai_telemetry_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['ai_telemetry_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_telemetry_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_telemetry_responses_hit'), ['hit'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_telemetry_responses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_telemetry_responses_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_telemetry_responses_topic_id'), ['topic_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_telemetry_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_telemetry_responses_topic_id'))
        batch_op.drop_index(batch_op.f('ix_ai_telemetry_responses_run_id'))
        batch_op.drop_index(batch_op.f('ix_ai_telemetry_responses_id'))
        batch_op.drop_index(batch_op.f('ix_ai_telemetry_responses_hit'))

    op.drop_table('ai_telemetry_responses')
    with op.batch_alter_table('sentiment_run_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentiment_run_logs_id'))
        batch_op.drop_index(batch_op.f('ix_sentiment_run_logs_account_id'))

    op.drop_table('sentiment_run_logs')
    with op.batch_alter_table('sentiment_knowledge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentiment_knowledge_id'))
        batch_op.drop_index(batch_op.f('ix_sentiment_knowledge_account_id'))

    op.drop_table('sentiment_knowledge')
    with op.batch_alter_table('ai_telemetry_topic_briefings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_telemetry_topic_briefings_id'))
        batch_op.drop_index('idx_tb_topic')

    op.drop_table('ai_telemetry_topic_briefings')
    with op.batch_alter_table('ai_telemetry_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_telemetry_runs_topic_id'))
        batch_op.drop_index(batch_op.f('ix_ai_telemetry_runs_id'))

    op.drop_table('ai_telemetry_runs')
    with op.batch_alter_table('ai_telemetry_query_hits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_telemetry_query_hits_id'))
        batch_op.drop_index('idx_qh_topic')

    op.drop_table('ai_telemetry_query_hits')
    with op.batch_alter_table('ai_telemetry_cell_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_telemetry_cell_insights_id'))
        batch_op.drop_index('idx_ci_topic')

    op.drop_table('ai_telemetry_cell_insights')
    with op.batch_alter_table('user_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_memberships_id'))

    op.drop_table('user_memberships')
    op.drop_table('user_check_usage')
    with op.batch_alter_table('sentiment_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentiment_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_sentiment_accounts_id'))

    op.drop_table('sentiment_accounts')
    with op.batch_alter_table('payment_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_sessions_stripe_session_id'))
        batch_op.drop_index(batch_op.f('ix_payment_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_payment_sessions_id'))

    op.drop_table('payment_sessions')
    with op.batch_alter_table('detection_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detection_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_detection_records_id'))
        batch_op.drop_index(batch_op.f('ix_detection_records_created_at'))

    op.drop_table('detection_records')
    with op.batch_alter_table('ai_telemetry_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_telemetry_topics_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_telemetry_topics_id'))

    op.drop_table('ai_telemetry_topics')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('sentiment_platforms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentiment_platforms_id'))
        batch_op.drop_index(batch_op.f('ix_sentiment_platforms_code'))

    op.drop_table('sentiment_platforms')
    with op.batch_alter_table('sales_leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_leads_id'))

    op.drop_table('sales_leads')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_slug'))
        batch_op.drop_index(batch_op.f('ix_memberships_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('contact_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_submissions_id'))

    op.drop_table('contact_submissions')
    op.drop_table('anonymous_check_usage')
    # ### end Alembic commands ###
